arg_dict = {
    "input_perturbation": 0,
    "pretrained_model_name_or_path": None,
    "revision": None,
    "dataset_name": None,
    "dataset_config_name": None,
    "train_data_dir": None,
    "image_column": "image",
    "caption_column": "text",
    "max_train_samples": None,
    "validation_prompts": None,
    "output_dir": "sd-model-finetuned",
    "cache_dir": None,
    "seed": None,
    "resolution": 512,
    "center_crop": False,
    # "random_flip": True,
    "train_batch_size": 16,
    "num_train_epochs": 100,
    "max_train_steps": None,
    "gradient_accumulation_steps": 1,
    # "gradient_checkpointing": True,
    "learning_rate": 1e-4,
    "scale_lr": False,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 500,
    "snr_gamma": None,
    # "use_8bit_adam": True,
    # "allow_tf32": True,
    # "use_ema": True,
    "non_ema_revision": None,
    "dataloader_num_workers": 0,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 1e-2,
    "adam_epsilon":1e-08,
    "max_grad_norm": 1.0,
    # "push_to_hub": True,
    "hub_token": None,
    "hub_model_id": None,
    "logging_dir": "logs",
    "mixed_precision": None,
    "report_to": "tensorboard",
    "local_rank": -1,
    "checkpointing_steps": 500,
    "checkpoints_total_limit": None,
    "resume_from_checkpoint": None,
    # "enable_xformers_memory_efficient_attention": True,
    "noise_offset": 0,
    "validation_epochs": 5,
    "tracker_project_name": "text2image-fine-tune"
}
